/**
 * Reads the bytes behind the reference assets a slide was given.
 *
 * Split from `reference-image.ts` so the selection rules stay testable without
 * a database or a bucket, and split from the activity so the activity does not
 * grow a third concern. Everything eligibility-related has already happened by
 * the time this runs; this only fetches.
 *
 * It is called inside `renderSlideActivity` rather than during planning on
 * purpose. Temporal writes every activity result into workflow history, so a
 * reference image carried in `GenerationPlan` would be replayed and retained
 * for the whole history retention period — the same reason the file header in
 * `worker/activities/generation.ts` keeps generated bytes out of activity
 * results. Storage keys travel between activities; bytes never do.
 */

import { GenerationError } from "@/lib/generation/litellm";
import type { ReferenceAssetRef, ReferenceImage } from "@/lib/generation/reference-image";
import { prisma } from "@/lib/db";
import { getObject } from "@/lib/s3";

/**
 * Resolves goal asset ids into reference candidates, scoped to their owner.
 *
 * `userId` is part of the query rather than checked afterwards: goal rows hold
 * bare asset ids with no foreign key, so nothing at the database level stops an
 * id from another workspace being stored there. Ids that match nothing — a
 * deleted asset, or one that was never theirs — are returned as `missing` for
 * the caller to report, not treated as an empty selection.
 */
export async function resolveReferenceAssets(input: {
  userId: string;
  logoAssetId: string | null;
  referenceAssetIds: string[];
  imageAssetIds: string[];
}): Promise<{
  logo: ReferenceAssetRef | null;
  references: ReferenceAssetRef[];
  slideSources: (ReferenceAssetRef | null)[];
  missing: string[];
}> {
  const ids = [
    ...(input.logoAssetId ? [input.logoAssetId] : []),
    ...input.referenceAssetIds,
    ...input.imageAssetIds,
  ];

  if (ids.length === 0) {
    return { logo: null, references: [], slideSources: [], missing: [] };
  }

  const rows = await prisma.asset.findMany({
    where: { id: { in: [...new Set(ids)] }, userId: input.userId },
    select: { id: true, name: true, mimeType: true, sizeBytes: true, storageKey: true },
  });

  const byId = new Map(rows.map((row) => [row.id, row]));

  const toRef = (id: string, role: ReferenceAssetRef["role"]): ReferenceAssetRef | null => {
    const row = byId.get(id);
    if (!row) return null;
    return {
      assetId: row.id,
      storageKey: row.storageKey,
      mime: row.mimeType,
      name: row.name,
      sizeBytes: row.sizeBytes,
      role,
    };
  };

  const missing = [...new Set(ids)].filter((id) => !byId.has(id));

  return {
    logo: input.logoAssetId ? toRef(input.logoAssetId, "logo") : null,
    references: input.referenceAssetIds
      .map((id) => toRef(id, "reference"))
      .filter((ref): ref is ReferenceAssetRef => ref !== null),
    // Index-matched to slide order, which is why the nulls stay in: a deleted
    // asset has to hold its place, or every later slide silently shifts onto
    // the wrong picture.
    slideSources: input.imageAssetIds.map((id) => toRef(id, "source")),
    missing,
  };
}

/**
 * Fetches the bytes for already-selected references.
 *
 * A reference that cannot be read is a `GenerationError`, which the workflow
 * lists as non-retryable: a deleted object or a key pointing nowhere fails
 * identically on all three attempts, and burning two more image-model calls to
 * confirm that costs money. A genuinely transient bucket failure surfaces as
 * whatever the SDK threw and stays retryable, which is why this does not wrap
 * every error indiscriminately.
 *
 * Silently generating without the reference is the one thing it must not do —
 * that is exactly the failure this whole change exists to remove.
 */
export async function loadReferenceImages(
  refs: ReferenceAssetRef[],
): Promise<ReferenceImage[]> {
  if (refs.length === 0) return [];

  return Promise.all(
    refs.map(async (ref) => {
      let bytes: Buffer;
      try {
        ({ bytes } = await getObject(ref.storageKey));
      } catch (err) {
        const name = (err as { name?: string })?.name;
        const status = (err as { $metadata?: { httpStatusCode?: number } })?.$metadata
          ?.httpStatusCode;

        if (name === "NoSuchKey" || name === "NotFound" || status === 404) {
          throw new GenerationError(
            `Reference asset "${ref.name}" is no longer in storage, so it cannot be used as a reference. Remove it from the goal or upload it again.`,
          );
        }
        throw err;
      }

      if (bytes.byteLength === 0) {
        throw new GenerationError(
          `Reference asset "${ref.name}" is empty, so it cannot be used as a reference.`,
        );
      }

      return { ...ref, bytes };
    }),
  );
}
